### ISSUE TITLE
Fix the sub-header items alignment when we have only one item

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx-template#10]
The screenshot is from https://github.com/IgniteUI/design-system-docfx.
![capture](https://user-images.githubusercontent.com/6439482/40976726-b0d3629e-68d7-11e8-910b-f27d149e4466.PNG)

**Comment by tiliev** [comment]
@StefanIvanov, I guess we do not need this anymore since we're going to have 2 links in the Indigo navigation:
![new-nav](https://user-images.githubusercontent.com/6439482/41836588-da5c662e-7863-11e8-8b91-7ce48001bc82.PNG)
Can you confirm?

**Comment by StefanIvanov** [comment]
CONFIRMED
