### ISSUE TITLE
Problem with global theming in Edge

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-docfx-template#135]
When dark theme is selected at a topic and a navigation to other ropic is triggered, the dark theme is not applied to the iframes of the newly navigated opic

**Comment by dkamburov** [comment]
Here's the pull request for the theming widget https://github.com/IgniteUI/igniteui-angular-samples/pull/1740
I believe the root cause is similar.

**Comment by ChronosSF** [comment]
Assigning this to myself. We fixed the Theming Widget issue in Edge and there is a PR for IE so after 9.0 is released this will be obsolete.

**Comment by MayaKirova** [comment]
Resolved with IgniteUI/igniteui-angular-samples#1740
