### ISSUE TITLE
Side Affix' are broken

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-docfx-template#206]
This is probably caused, after changing the h2 headers to h1. 
![image](https://user-images.githubusercontent.com/25771040/92738416-976da780-f384-11ea-8a34-17597341fc29.png)

Let's take this further and implement a couple of things:
- the right TOC to be with default expanded state
- add a focus indicator that will show where exactly in the topic are you, like in the angular docs:
![image](https://user-images.githubusercontent.com/11193764/94012147-10232980-fdb1-11ea-8421-f9b202468684.png)

**Comment by zdrawku** [comment]
Part of 2.8.0 version
