### ISSUE TITLE
Broken TOC styles when having 2-level nesting

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx-template#25]
When having more than 1 nested level of menu items in the TOC, the style is broken.

Screenshot:

![broken-toc](https://user-images.githubusercontent.com/6439482/43006210-c74e8240-8c3d-11e8-8708-ac949247f75f.PNG)

**Comment by tiliev** [comment]
This issue is partially fixed in 1.0.13-beta.1.
What's not fixed is:

![issues](https://user-images.githubusercontent.com/6439482/43319075-115b2ca8-91ac-11e8-9da2-e27ccc3e390a.PNG)

1. "new" icon is not properly aligned when it is nested in > level 2.
2.  selection style of a menu item with children should be discussed.

**Comment by simeonoff** [comment]
Closed via https://github.com/IgniteUI/igniteui-docfx-template/pull/31
