### ISSUE TITLE
Code view for one calendar sample is missing

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx-template#250]
Open - https://www.infragistics.com/products/ignite-ui-angular/angular/components/calendar#week-numbers
Check the Week numbers sample:

![image](https://user-images.githubusercontent.com/11193764/101149553-c57f2280-3627-11eb-8ff9-0ba523b2a317.png)

There is no Code View

**Comment by dobromirts** [comment]
This issue is related to #https://github.com/IgniteUI/igniteui-docfx/issues/2451 and the fix for the iframe-ids will fix it.
