### ISSUE TITLE
Docfx Template new structure

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-docfx-template#259]
1. Clean up /styles folder - it should be used only for styles, not having other logic (as it currently has)
2. Configure a build, which outputs only the files necessary for the docfx template to work properly 
3. Remove the custom logic from the docfx.js file
4. Update to ES6 or Typescript
5. Use npm packages instead of minified copy code

**Comment by zdrawku** [comment]
Merged with https://github.com/IgniteUI/igniteui-docfx-template/issues/228
