### ISSUE TITLE
Styling when using the expansion indicators

### ISSUE THREAD

**Issue by pamelabrasil** [IgniteUI/igniteui-docfx-template#26]
the headers should be highlighted or emphasized in some way. Currently they blend in when there are many expansion indicators.

The indentation of the topics that are expandable is left aligned. It should be indented under the header. The topics that are opened under the parent node should also be indented.
 
![styling toc](https://user-images.githubusercontent.com/11391376/43012037-3cfb5d9a-8c13-11e8-9454-85bd3ae6f699.png)

**Comment by simeonoff** [comment]
Closed via https://github.com/IgniteUI/igniteui-docfx-template/pull/31
