### ISSUE TITLE
When clicking on expandable item, it should expand

### ISSUE THREAD

**Issue by pamelabrasil** [IgniteUI/igniteui-docfx-template#27]
currently it is set up that the parent node should have content before it can be expanded. This works well in certain situations. however in some cases, we don't want the parent node to have content. Once it is clicked it should show the items underneath without the need to load a 'landing page'.

Review the DocFX documentation table of contents for an example
https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html

**Comment by pamelabrasil** [comment]
In certain situations though a landing page might be required and information added. So the option of having a landing page and not should be allowed.

**Comment by simeonoff** [comment]
Closed via https://github.com/IgniteUI/igniteui-docfx-template/pull/31
