### ISSUE TITLE
Docfx routing animations 

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-docfx-template#288]
Now that we are transforming the docfx site into a SPA, we need some animations when a new article is loaded.
Related to #229 

The working branch is -  [**hPopov/transform-to-spa**](https://github.com/IgniteUI/igniteui-docfx-template/tree/hPopov/transform-to-spa)

Current Ignite UI for jQuery UX - [documentation](https://www.igniteui.com/help/iggrid-overview)

To work with this branch you need to :
 
- Build the docfx template with `npm run build:dev`
- Go to the dist folder and run `npm link`
- Go to the docfx project, which uses the template and run `npm link igniteui-docfx-template`
- Then run the docfx project with `npm run start`  and the site will start, but no content will be rendered, so you need to go to **http://localhost:3000/components/general/getting-started.html**

Development branch https://github.com/IgniteUI/igniteui-docfx-template/tree/hPopov/transform-to-spa

**Comment by zdrawku** [comment]
Merged in the initial PR
