### ISSUE TITLE
List all composing elements that might need custom styling for Slingshot

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx-template#297]
Make a list of all composing visual elements, like:
- Code snippets
- All three types of Notes (warning, info, error)
![image](https://user-images.githubusercontent.com/11193764/115858438-9e3ebb80-a437-11eb-8a4a-89b9b252a38c.png)
![image](https://user-images.githubusercontent.com/11193764/115858471-abf44100-a437-11eb-872c-201013219d61.png)
![image](https://user-images.githubusercontent.com/11193764/115858564-ca5a3c80-a437-11eb-9a26-6ca7bfb473a4.png)

- Side affic for in-page navigation
- TOC and toc list items
- Toolbar 
- Breadcrumb
- and etc.

**Comment by dobromirts** [comment]
1. Typography
2. Text Selection - color and background
![selection](https://user-images.githubusercontent.com/46093564/116383042-2bf71e00-a81f-11eb-8326-6b5c01c492b2.png)
3. Anchor link
![anchor-link](https://user-images.githubusercontent.com/46093564/116383111-3a453a00-a81f-11eb-9f06-a140c78707a8.png)
4. External link
![external-link](https://user-images.githubusercontent.com/46093564/116383170-47fabf80-a81f-11eb-9c30-f4bcaf847a4b.png)
5. Tables
![table](https://user-images.githubusercontent.com/46093564/116383259-5943cc00-a81f-11eb-8f4f-ecc6e70d3899.png)
6. Toc badges
![toc-badges](https://user-images.githubusercontent.com/46093564/116383335-682a7e80-a81f-11eb-9d9a-1a9533572601.png)
7. Toc filter/search
![toc-filter](https://user-images.githubusercontent.com/46093564/116383385-76789a80-a81f-11eb-87f1-11785e7ba9ff.png)

**Comment by StefanIvanov** [comment]
thanks @dobromirts
