### ISSUE TITLE
Update Google Analytics tracking scripts

### ISSUE THREAD

**Issue by jasonzajac** [IgniteUI/igniteui-docfx-template#314]
Work with marketing (@jasonzajac) on updating Google Analytics scripts to accommodate SPA-like behavior. Will need to discuss and test best way to handle. It might be possible to handle in GTM, but I know tracking in IgniteUI.com had to utilize some template-based changes to accommodate the dynamic loading of new page content.

**Comment by HristoP96** [comment]
Done!
