### ISSUE TITLE
Improve side-nav design of the documentation

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-docfx-template#318]
Improve the side-nav design of the tree view navigation with topic titles on the left for the template of Ignite UI for Angular.

**Comment by tosharky** [comment]
Since I can't attach the XD file here, I will share the dev link here. Let me know if you need the file I will send it directly to you @desig9stein

https://xd.adobe.com/view/b580b071-0b27-45d0-9f53-4ecb026c0615-e0d3/
