### ISSUE TITLE
Upgrade template to latest versions

### ISSUE THREAD

**Issue by brianlagunas** [IgniteUI/igniteui-docfx-template#376]
The template is currently outdated.

Firstly, it is difficult to build on new systems because many dependencies are old and rely on old versions of python and windows build tools (VS2017). Current installers to not provide these old dependencies and they are difficult to find and setup. All dependencies should be updated to the latest version.

Secondly, it is missing many built-in features from Docfx such as tabs and the ability to include content using file includes.

The custom plugin is also built against the old version of docfx (2.47) which requires that specific version of docfx or it will not build.

**Comment by kdinev** [comment]
@brianlagunas Closing this issue, as our template now supports the latest DocFX (2.64.0 at the moment). All dependent repositories have been updated to install docfx as a `dotnet tool`.
