### ISSUE TITLE
Code Viewer show code incorrectly in Razor tab

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-docfx-template#381]
Code Viewer shows code with comments incorrectly in Razor tab, e.g.

https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid-column-types?gasource=(direct)&gamedium=(none)&gacampaign=(not%20set)&gaterm=&gagclid=#blazor-column-types-example

![image](https://user-images.githubusercontent.com/11665978/175114134-1a0aae31-852e-49b0-88b8-9c69a55f63e3.png)

**Comment by zdrawku** [comment]
@HUSSAR-mtrela could you please mark the incorect part and whats the expected result?

**Comment by HUSSAR-mtrela** [comment]
@zdrawku 
[Razor comments](https://github.com/IgniteUI/igniteui-blazor-examples/blob/vnext/samples/grids/data-grid/column-types/App.razor#L24) start with ```@*``` and ends with ```*@``` tags and I highlighted them in red box. 

Also, formatting style of C# Comments ```//```, ```/*```, ```*/``` should be applied only within the [@code](https://github.com/IgniteUI/igniteui-blazor-examples/blob/vnext/samples/grids/data-grid/column-types/App.razor#L56) section of .razor files.
 

![image](https://user-images.githubusercontent.com/11665978/181117009-15ce3676-e5a8-470c-9544-c58578389d5b.png)

**Comment by zdrawku** [comment]
Adding it to the sprint.

**Comment by HUSSAR-mtrela** [comment]
@zdrawku, @dobromirts  I set severity to high because we need to have this fix soon.

**Comment by zdrawku** [comment]
@HUSSAR-mtrela, ah yes, we've been moving it around boards for some time now. Adding it as part of the current sprint. Will try to do a PR by the end of the week.
