### ISSUE TITLE
NOTE blocks are missing styling icon and boarder

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-docfx-template#414]
NOTE blocks are missing styling icon and boarder in topics that were generated using latest version of [igniteui-docfx-template](https://github.com/IgniteUI/igniteui-docfx-template). 

For example, [staging](https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/charts/features/chart-axis-gridlines):

![image](https://user-images.githubusercontent.com/11665978/217885366-7fa2ba2b-6c1d-4d03-a648-377ea1b15947.png)

For example, [production](https://infragistics.com/products/ignite-ui-blazor/blazor/components/charts/features/chart-axis-gridlines):
![image](https://user-images.githubusercontent.com/11665978/217885460-45b3ba74-a684-4abe-b571-4ccb76025198.png)

**Comment by zdrawku** [comment]
@hanastasov I am adding this bug as part of the sprint as it is a regression
