### ISSUE TITLE
Define default style for images including responsive behavior

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-docfx-template#420]
Currently we have these rules:

**default**
https://github.com/IgniteUI/igniteui-docfx-template/blob/25dca7700e114d4056f7017f8b6858d0b234b716/src/styles/shared/components/_responsive.scss#L1-L3
and **slingshot**
https://github.com/IgniteUI/igniteui-docfx-template/blob/25dca7700e114d4056f7017f8b6858d0b234b716/src/styles/slingshot/main.scss#L39-L44

In the case of Slingshot the rule seems to be outdated since images are not normally direct children of .article-container, I don't know if they can ever be.

For this reason, we end up customizing each image in both Ignite and App Builder repos, like so:
```
<img class="responsive-img" style="box-shadow: 5px -4px 13px 1px grey" src="./images/IIS-config.gif" alt="IIS config" />
```
instead of using standard Markdown syntax:
```
![IIS config](./images/IIS-config.gif)
```

Also, not capping width to 100%, will probably break the article layout, so I think we should make this by default in both variants:

```css
.responsive-img, 
article img:not(.raw) { 
    max-width: 100%;
}
```

Adding an opt-out `.raw` class in the edge case we need to opt out of it.

> Note: as reference Github markdown preview inserts max-width: 100% to the images.

For the **shadow**, we have it in many images in App Builder, but it's something that we won't want to be always applied.

So perhaps can be opt-in as:
```css
img.screencapture,
.screencapture img
{
    box-shadow: 5px -4px 13px 1px grey;
}
```

then use like:
```html
<img class="screencapture" src="./images/IIS-config.gif" alt="IIS config" />
or
<span class="screencapture">![IIS config](./images/IIS-config.gif)</span>
```

**Comment by zdrawku** [comment]
@dobromirts my understanding is that the 100% width wont be introduced through another class, rather apply it directly with a css selector for all images part of the page.

**Comment by pmoleri** [comment]
I updated `screen-capture` to `screencapture` since is normally written this way.

**Comment by pmoleri** [comment]
@zdrawku it would be great if some visual designer reviews the box-shadow styles.
They seem a bit strong to my untrained eye. @andiesm813 is OOO today.
Also, let's consider that this new class will be applicable to both IgniteUI and AppBuilder repos.

**Comment by andiesm813** [comment]
Hey guys! could we change the box-shadow values to these?
`box-shadow: 0 0 13px 0 #0000004d;`
