### ISSUE TITLE
CSS font colors are too dark for some elements

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-docfx-template#426]
go to
https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/layouts/dock-manager#customization

Code Viewer shows the following items with dark blue color which is not readable on black background:
"::parts", "-header" "-button"

![image](https://user-images.githubusercontent.com/11665978/228001058-56fa69f2-ab8a-4965-9c30-ed593b185c6c.png)

**Comment by zdrawku** [comment]
@dobromirts I believe these colors are automatic from the highlight-js library?

**Comment by dobromirts** [comment]
Currently we are using colors based on the theme palette defined here
![styles](https://user-images.githubusercontent.com/46093564/228805302-4b4dd9c1-26c3-45f0-8b74-9099c56fdc0e.png)
for these elements .hljs-bullet,.hljs-selector-tag,.hljs-selector-id,.hljs-selector-class,.hljs-selector-attr,.hljs-selector-pseudo and we can add styling enhancements for it.
