### ISSUE TITLE
Improve Razor syntax code snippets style

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx-template#440]
Open any [Blazor documentation](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid) and check the Razor syntax styling:

Now:
![image](https://user-images.githubusercontent.com/11193764/234500635-3c5d6ba1-683d-489c-b9b3-416a674ec405.png)

Proposed styling:
![image](https://user-images.githubusercontent.com/11193764/234574195-0819f5ef-589d-4a50-9599-a5a71263a11e.png)

We can use plugin like hljs in order to beautify it, for example:
https://github.com/IgniteUI/igniteui-docfx-template/pull/436

**Comment by dobromirts** [comment]
With the latest template version the change is already included:
![new-template-version-razor](https://github.com/IgniteUI/igniteui-docfx-template/assets/46093564/0b0e3c42-cf96-4160-a668-d39fbbdd2ce2)

**Comment by dobromirts** [comment]
Fixed on staging and prod: 
![image](https://github.com/IgniteUI/igniteui-docfx-template/assets/46093564/cf9c325a-b3b2-4b9b-b347-946f2f1cae86)
