### ISSUE TITLE
Sandbox links point to wrong Angular DV sample repo

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-docfx-template#451]
open and DV topic in Angular docs, e.g.
https://staging.infragistics.com/products/ignite-ui-angular/angular/components/bullet-graph#angular-bullet-graph-example

click on Sandbox button

sandbox link points to old igniteui-live-editing-samples repo, e.g.
https://codesandbox.io/s/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos-dv/gauges/bullet-graph/animation
instead, sandbox link should point to the igniteui-angular-examples, e.g.
https://codesandbox.io/s/github/IgniteUI/igniteui-angular-examples/tree/master/samples/gauges/bullet-graph/animation

**Comment by dobromirts** [comment]
@HUSSAR-mtrela  The links are fixed to point the correct DV samples repository. However, errors persist when opening the CodeSandbox. The same issue arises when accessing the sample through the provided link: https://github.com/IgniteUI/igniteui-angular-examples/tree/vnext/samples/charts/category-chart/annotations-all.

Additionally, we can enable StackBlitz for the Angular DV samples, but certain improvements are necessary for them to function correctly:

1. Modify the reference for 'tsconfig.app.json' in the 'angular.json' file. In the generated sample variant, this file is not located in the 'src' folder. https://github.com/IgniteUI/igniteui-angular-examples/blob/vnext/samples/charts/category-chart/annotations-callouts/angular.json

2. Update 'polyfills.ts' to match the configuration at https://github.com/IgniteUI/igniteui-angular-samples/blob/master/src/polyfills.ts.
