### ISSUE TITLE
3rd level toc item has its "new" tag not aligned

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx-template#54]
## Steps to reproduce:
1. Open https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid_row_editing.html
2. Open `Data Grid` and `Editing`.

## Result

![capture](https://user-images.githubusercontent.com/6439482/47997307-06807200-e104-11e8-95d7-992be1515201.PNG)

## Expected result

The NEW tags should be right-aligned.

**Comment by SlavUI** [comment]
There will be no third level for the time being will reopen if necessary
