### ISSUE TITLE
Resources invalidation

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx-template#56]
Please implement invalidation for the following resources:
- [x] All JS and CSS files
- [x] Language resources
- [x] StackBlitz samples resources (related to https://github.com/IgniteUI/igniteui-docfx/issues/765)

**Comment by damyanpetev** [comment]
@tiliev Unless you are generating both bundles with different names and the HTML template for those, query should be an alright approach :)
Thinking you should automate it somehow - a hash based on file content, the build version or something along those lines as long as we don't have to maintain it.
