### ISSUE TITLE
StackBlitz buttons do not work in Edge

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx-template#62]
StackBlitz buttons do not work in Edge on local environment. They work on staging and on prod.
This error appears:

![ignav](https://user-images.githubusercontent.com/6439482/49867590-9906e600-fe13-11e8-84fe-4cd998a6f38c.PNG)

It seems that navigation.js file from infragistics.com is not loaded properly.

**Comment by zdrawku** [comment]
The old edge and IE11 should no longer support live-editing, only a code-view.
