### ISSUE TITLE
Drop bLazy in favor of Lazysizes

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx-template#78]
Please drop [bLazy ](https://github.com/dinbror/blazy)in favor of [Lazysizes](https://github.com/aFarkas/lazysizes). The latter is an actively developed plugin, more popular and supports `Intersection Observer API`.

After [this ](https://github.com/IgniteUI/igniteui-docfx-template/pull/76)PR is merged, we'll have both plugins.

**Comment by HristoP96** [comment]
We removed the the bLazy when we added the new architecture
