### ISSUE TITLE
Incorrect link to GitHub in all grid, tree grid and hierarchical grid topics

### ISSUE THREAD

**Issue by PlamenaMiteva** [IgniteUI/igniteui-docfx-template#87]
Incorrect link to GitHub in all grid, tree grid and hierarchical grid topics

**Comment by zdrawku** [comment]
@HristoP96 As we discussed we need to remove View on GitHub buttons for all Grid topics. Add this task to your queue

**Comment by HristoP96** [comment]
@zdrawku  This is the issue that will cover the requirement:

[https://github.com/IgniteUI/igniteui-docfx-template/issues/104](https://github.com/IgniteUI/igniteui-docfx-template/issues/104)

**Comment by HristoP96** [comment]
This issue is fixed with this PR - [https://github.com/IgniteUI/igniteui-docfx-template/pull/105](https://github.com/IgniteUI/igniteui-docfx-template/pull/105)
